'use client';

import {
  BrainCircuit,
  Sparkles,
  Activity,
  FlaskConical,
  Pill,
  AlertTriangle,
} from 'lucide-react';

import { Card, CardContent } from '@/components/ui/card';
import { Progress } from '@/components/ui/progress';
import { Badge } from '@/components/ui/badge';

interface DiseaseProbability {
  name: string;
  probability: number;
}

interface TreatmentItem {
  medicine: string;
  dosage: string;
  frequency: string;
}

interface DiagnosisPanelProps {
  diseases: DiseaseProbability[];
  recommendedTests: string[];
  recommendedTreatment: TreatmentItem[];
}

export function DiagnosisPanel({
  diseases,
  recommendedTests,
  recommendedTreatment,
}: DiagnosisPanelProps) {
  return (
    <Card className="shadow-lg border-blue-100">

      <CardContent className="p-8">

        <div className="flex items-center gap-4 mb-8">

          <div className="rounded-full bg-blue-100 p-4">

            <BrainCircuit className="h-8 w-8 text-blue-600" />

          </div>

          <div>

            <h2 className="text-3xl font-bold">

              Gemma AI Diagnosis

            </h2>

            <p className="text-slate-500">

              Clinical decision support powered by AI

            </p>

          </div>

          <Badge className="ml-auto">

            <Sparkles className="mr-1 h-3 w-3" />

            AI Generated

          </Badge>

        </div>

        {/* Disease Prediction */}

        <div className="mb-10">

          <div className="flex items-center gap-2 mb-5">

            <Activity className="text-red-600" />

            <h3 className="text-xl font-bold">

              Possible Conditions

            </h3>

          </div>

          <div className="space-y-5">

            {diseases.map((disease) => (

              <div key={disease.name}>

                <div className="flex justify-between mb-2">

                  <span className="font-medium">

                    {disease.name}

                  </span>

                  <span className="font-bold">

                    {disease.probability}%

                  </span>

                </div>

                <Progress value={disease.probability} />

              </div>

            ))}

          </div>

        </div>

        {/* Recommended Tests */}

        <div className="mb-10">

          <div className="flex items-center gap-2 mb-5">

            <FlaskConical className="text-purple-600" />

            <h3 className="text-xl font-bold">

              Recommended Tests

            </h3>

          </div>

          <div className="grid md:grid-cols-2 gap-4">

            {recommendedTests.map((test) => (

              <div
                key={test}
                className="rounded-lg border bg-slate-50 p-4"
              >
                🧪 {test}
              </div>

            ))}

          </div>

        </div>

        {/* Treatment */}

        <div>

          <div className="flex items-center gap-2 mb-5">

            <Pill className="text-green-600" />

            <h3 className="text-xl font-bold">

              Suggested Treatment

            </h3>

          </div>

          <div className="space-y-4">

            {recommendedTreatment.map((item) => (

              <div
                key={item.medicine}
                className="rounded-lg border p-5"
              >

                <div className="font-bold text-lg">

                  {item.medicine}

                </div>

                <p className="text-slate-600 mt-2">

                  {item.dosage}

                </p>

                <p className="text-slate-500">

                  {item.frequency}

                </p>

              </div>

            ))}

          </div>

        </div>

        <div className="mt-10 rounded-xl bg-amber-50 border border-amber-200 p-5">

          <div className="flex items-center gap-3">

            <AlertTriangle className="text-amber-600" />

            <strong>

              Clinical Notice

            </strong>

          </div>

          <p className="mt-3 text-slate-700 leading-7">

            These recommendations are generated by Gemma AI as a
            clinical decision-support tool. Final diagnosis,
            investigations, and treatment decisions remain the
            responsibility of the licensed healthcare professional.

          </p>

        </div>

      </CardContent>

    </Card>
  );
}