'use client';

import {
  Ambulance,
  BrainCircuit,
  AlertTriangle,
  Activity,
  Clock3,
  MapPinned,
  Sparkles,
} from 'lucide-react';

import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';

interface EmergencyAnalysisProps {
  severity?: number;
  condition?: string;
  recommendation?: string;
  nearestHospital?: string;
  estimatedArrival?: string;
}

export function EmergencyAnalysis({
  severity = 0,
  condition = '',
  recommendation = '',
  nearestHospital = '',
  estimatedArrival = '',
}: EmergencyAnalysisProps) {

  const severityLabel =
    severity >= 85
      ? 'Critical'
      : severity >= 60
      ? 'High'
      : severity >= 35
      ? 'Moderate'
      : 'Low';

  const badgeColor =
    severity >= 85
      ? 'destructive'
      : severity >= 60
      ? 'secondary'
      : 'default';

  return (

    <Card className="shadow-lg border-red-100">

      <CardContent className="p-8">

        <div className="flex items-center justify-between mb-8">

          <div className="flex items-center gap-4">

            <div className="rounded-full bg-red-100 p-4">

              <BrainCircuit className="h-8 w-8 text-red-600"/>

            </div>

            <div>

              <h2 className="text-3xl font-bold">

                Gemma Emergency Analysis

              </h2>

              <p className="text-slate-500">

                AI-powered emergency assessment

              </p>

            </div>

          </div>

          <Badge variant={badgeColor}>

            <Sparkles className="mr-2 h-3 w-3"/>

            {severityLabel}

          </Badge>

        </div>

        <div className="mb-8">

          <div className="flex justify-between mb-2">

            <span className="font-medium">

              Emergency Severity

            </span>

            <strong>

              {severity}%

            </strong>

          </div>

          <Progress value={severity}/>

        </div>

        <div className="grid lg:grid-cols-2 gap-6 mb-8">

          <Card>

            <CardContent className="p-5">

              <div className="flex items-center gap-3 mb-3">

                <Activity className="text-red-600"/>

                <strong>

                  Possible Condition

                </strong>

              </div>

              <p className="text-slate-700">

                {condition}

              </p>

            </CardContent>

          </Card>

          <Card>

            <CardContent className="p-5">

              <div className="flex items-center gap-3 mb-3">

                <Ambulance className="text-blue-600"/>

                <strong>

                  AI Recommendation

                </strong>

              </div>

              <p className="text-slate-700">

                {recommendation}

              </p>

            </CardContent>

          </Card>

        </div>

        <div className="grid md:grid-cols-2 gap-6 mb-8">

          <Card>

            <CardContent className="p-5">

              <div className="flex items-center gap-3 mb-3">

                <MapPinned className="text-green-600"/>

                <strong>

                  Recommended Hospital

                </strong>

              </div>

              <p>

                {nearestHospital}

              </p>

            </CardContent>

          </Card>

          <Card>

            <CardContent className="p-5">

              <div className="flex items-center gap-3 mb-3">

                <Clock3 className="text-purple-600"/>

                <strong>

                  Estimated Arrival

                </strong>

              </div>

              <p>

                {estimatedArrival}

              </p>

            </CardContent>

          </Card>

        </div>

        <div className="rounded-xl border border-red-200 bg-red-50 p-6">

          <div className="flex items-center gap-3 mb-3">

            <AlertTriangle className="text-red-600"/>

            <strong>

              Emergency Guidance

            </strong>

          </div>

          <p className="leading-7 text-slate-700">

            This assessment is generated by Gemma AI using the
            information provided. It assists emergency responders
            by estimating severity and recommending an appropriate
            hospital, but it does not replace professional medical
            judgment or emergency services.

          </p>

        </div>

      </CardContent>

    </Card>

  );

}